pipeline {
  agent none
  options {
    disableConcurrentBuilds()
  }
  stages {
  stage('checks') {
    agent {
      docker {
        image 'alpine:3.9'
        label 'linux'
      }
    }
    steps {
      sh label: "Find files with trailing whitespace", script: '! grep -n "[ \t]$" *.tex chapters/*.tex'
    }
  }
  stage('build') {
    agent {
      docker {
        image 'modelicaspec/latexml:20260212'
        label 'linux'
        alwaysPull true
      }
    }
    environment {
      HOME = '/tmp/jenkins'
    }
    steps {
      sh 'mkdir -p /tmp/jenkins'
      sh 'latexmk -pdf MLS.tex'
      sh 'latexml MLS.tex --includestyles --path=media --dest MLS.xml'
      sh 'latexmlpost MLS.xml -format html -pmml --splitat=chapter --splitnaming=labelrelative --navigationtoc=context --css=css/MLS.css --css=css/MLS-navbar-left.css --dest index.html'
      sh '.scripts/patch-viewport.sh'
      sh '.scripts/patch-body-ios-hover.sh'
      sh script: '! (find . -type l -xtype l | egrep \'.*\')', label: 'Verify symbolic links work'
      sh 'tar czf MLS.tar.gz *.html *.css media/ css/'
      archiveArtifacts artifacts: 'MLS.tar.gz', fingerprint: true
      archiveArtifacts artifacts: 'MLS.pdf', fingerprint: true
      stash name: 'MLS', includes: '*.html,*.css,MLS.pdf,media/**,css/**,MLS.tar.gz'
    }
  }
  stage('upload') {
    when {
      allOf {
        not {
          changeRequest()
        }
        anyOf {
          buildingTag()
          anyOf {
            branch 'jenkins'
            branch 'master'
            branch 'maint/**'
          }
        }
      }
      beforeAgent true
    }
    agent {
      label 'linux'
    }
    steps {
      unstash name: 'MLS'
      sh "test ! -z ${env.GIT_BRANCH}"
      sshagent (credentials: ['Hudson-SSH-Key']) {
        sh 'ssh-keyscan github.com >> ~/.ssh/known_hosts'
        sh "test -d specification.modelica.org || git clone git@github.com:modelica/specification.modelica.org"
        sh "cd specification.modelica.org/ && git fetch && git reset --hard origin/master"
        sh "rm -rf  'specification.modelica.org/${env.GIT_BRANCH}' && mkdir -p  'specification.modelica.org/${env.GIT_BRANCH}'"
        sh "cp -a *.html *.css MLS.pdf media css 'specification.modelica.org/${env.GIT_BRANCH}'"
        sh """
        cd specification.modelica.org
        git add '${env.GIT_BRANCH}'
        if ! git diff-index --quiet origin/master --; then
          git config user.name "Automatic Build"
          git config user.email "noreply@modelica.org"
          git commit --amend -m "Initial commit"
          git push -f
        fi
        """
      }
    }
  }
  stage('index') {
    agent {
      label 'linux'
    }
    when {
      allOf {
        not {
          changeRequest()
        }
        branch 'master'
      }
      beforeAgent true
    }
    steps {
      script {
        docker.image('modelicaspec/markdown:20190307').inside {
          sh 'python3 .CI/index.py'
        }
      }
      sshagent (credentials: ['Hudson-SSH-Key']) {
        sh 'ssh-keyscan github.com >> ~/.ssh/known_hosts'
        sh "test -d specification.modelica.org || git clone git@github.com:modelica/specification.modelica.org"
        sh "cd specification.modelica.org/ && git fetch && git reset --hard origin/master"
        sh "cp -a index.html specification.modelica.org/"
        sh """
        cd specification.modelica.org
        git add index.html
        if ! git diff-index --quiet origin/master --; then
          git commit --amend -m "Initial commit"
          git push -f
        fi
        """
      }
    }
  }
  }
}
