== The Modelica Standard Library
:id: the-modelica-standard-library

In order that a modeler can quickly build up system models, it is important that libraries of the most commonly used components are available, ready to use, and sharable between applications.
For this reason, the Modelica Association develops and maintains a growing _Modelica Standard Library_ called `package Modelica`.
For an overview of the current version see https://github.com/modelica/ModelicaStandardLibrary.
This is a free library that can be used without essential restrictions, e.g., in commercial Modelica simulation environments.
The Modelica Standard Library is tool-neutral, and relies on a small library, ModelicaServices, that each conformant tool must implement to handle tool-specific couplings, e.g., for animation.
Furthermore, other people and organizations are developing free and commercial Modelica libraries.
For information about these libraries and for downloading the free libraries see https://modelica.org/libraries/.