[bibliography]
== Bibliography

[[BenvenisteEtAl2003SynchronousTwelveYearsLater,Benveniste, Caspi, Edwards, Halbwachs, Le Guernic, and Simone 2003]]
Benveniste, Albert; Caspi, Paul; Edwards, Stephen A.; Halbwachs, Nicolas; Le Guernic, Paul; Simone, Robert de (2003). "The Synchronous Languages Twelve Years Later." In: _Proceedings of the IEEE_, 91(1). https://doi.org/10.1109/JPROC.2002.805826 (cit. on p. 240).

[[Buerger2019SelectiveModel,Bürger 2019]]
Bürger, Christoff (2019). "Modelica language extensions for practical non-monotonic modelling: on the need for _selective_ model extension." In: _Proceedings of the 13th International Modelica Conference_, Regensburg, Germany, Mar 4-6, pp. 277-288. https://doi.org/10.3384/ecp19157277

[[ColacoPouzet2003ClocksFirstClass,Colaço and Pouzet 2003]]
Colaço, Jean-Louis; Pouzet, Marc (2003). "Clocks as First Class Abstract Types." In: _Third International Workshop on Embedded Software, EMSOFT 2003_, Philadelphia, Pennsylvania, USA. https://doi.org/10.1007/978-3-540-45212-6_10. http://www.di.ens.fr/~pouzet/lucid-synchrone/papers/emsoft03.ps.gz

[[GettextManual,Drepper, Meyering, Pinard, and Haible 2020]]
Drepper, Ulrich; Meyering, Jim; Pinard, François; Haible, Bruno (2020). "GNU gettext tools, version 0.21." https://www.gnu.org/software/gettext/manual/

[[ElmqvistOtterCellier1995InlineIntegration,Elmqvist, Otter, and Cellier 1995]]
Elmqvist, Hilding; Otter, Martin; Cellier, Francois E. (1995). "Inline Integration: A New Mixed Symbolic/Numeric Approach for Solving Differential-Algebraic Equation Systems." In: _Proceedings of ESM’95, European Simulation Multiconference_, Prague, Czech Republic, June 5-8, pp. xxiii-xxxiv. https://www.semanticscholar.org/paper/Inline-Integration%3A-A-New-Mixed-Symbolic%2FNumeric-Elmqvist-Otter/b696154cbfb9c82dd4983abbd45ed639a4d5c32c

[[ForgetEtAl2008MultiPeriodic,Forget, Boniol, Lesens, and Pagetti 2008]]
Forget, Julien; Boniol, Frédéric; Lesens, David; Pagetti, Claire (2008). "A Multi-Periodic Synchronous Data-Flow Language." In: _11th IEEE High Assurance Systems Engineering Symposium (HASE'08)_, Nanjing, China, Dec 3-5, pp. 251-260. https://doi.org/10.1109/HASE.2008.47

[[Harel1987Statecharts,Harel 1987]]
Harel, David (1987). "Statecharts: A Visual Formalism for Complex Systems." _Science of Computer Programming_, 8, pp. 231-274. https://doi.org/10.1016/0167-6423(87)90035-9

[[Pantelides1988ConsistentInitialization,Pantelides 1988]]
Pantelides, Constantinos C. (1988). "The Consistent Initialization of Differential-Algebraic Systems." _SIAM Journal on Scientific and Statistical Computing_, 9(2), pp. 213-231. https://doi.org/10.1137/0909014

[[Pouzet2006LucidSynchrone30,Pouzet 2006]]
Pouzet, Marc (2006). "Lucid Synchrone, Version 3.0, Tutorial and Reference Manual." http://www.di.ens.fr/~pouzet/lucid-synchrone/

[[ThummelEtAl2005InverseModels,Thümmel, Looye, Kurze, Otter, and Bals (2005)]]
Thümmel, Michael; Looye, Gertjan; Kurze, Matthias; Otter, Martin; Bals, Johann (2005). "Nonlinear Inverse Models for Control." In: _Proceedings of 4th International Modelica Conference_, ed. G. Schmitz, Hamburg, Germany, Mar 7-8. https://modelica.org/events/Conference2005/online_proceedings/Session3/Session3c3.pdf