= Modelica Language Specification
:sectnums:
:sectnumlevels: 4
// :sectlinks:
:toc-title: Contents
:toc: left
:toclevels: 4
:idprefix:
:idseparator: -
:xrefstyle: short
// :docinfodir: docs
:stem: latexmath
:source-highlighter: pygments
:nofooter:
:favicon: images/favicon.svg
// :icons: font
:subs=none

++++
<style>
/*
:root {
  --ma-bg-color: #1b1b1b;
  --ma-fg-color: #fff;
  --ma-blue: #0062cc;
  --ma-red: #dc3545;
}
*/

:root,[data-ma-theme="light"] {

    --ma-nav-height: 60px;

    --ma-body-color: #212529;
    --ma-body-bg: #fff;
    --ma-secondary-bg: rgba(240, 240, 240, 1);
    --ma-tertiary-color: rgba(33, 37, 41, 0.5);
    --ma-tertiary-bg: #f8f9fa;

    --ma-primary-bg-subtle: #cfe2ff;
    --ma-primary-border-subtle: #9ec5fe;

    --ma-success-bg-subtle: #d1e7dd;
    --ma-success-border-subtle: #a3cfbb;

    --ma-light-bg-subtle: #fcfcfd;
    --ma-light-border-subtle: #e9ecef;

    --ma-example-bg: #cff4fc;
    --ma-example-border-color: #0dcaf0;



    --ma-border-color: #dee2e6;

    --ma-pre-bg: #f8f9fa;

    --ma-font-sans-serif: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    --ma-font-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;

    --ma-blue: #0062cc;
    /*--ma-blue: #5ea9f0;*/
    --ma-red: #dc3545;

    .content img {
        filter: none;
    }
}

[data-ma-theme="dark"] {
    --ma-body-color: #dee2e6;
    --ma-body-bg: #212529;
    --ma-secondary-bg: #343a40;
    --ma-blue: #488ad0;
    --ma-border-color: #495057;
    --ma-pre-bg: #1b1f22;

    --ma-light-bg-subtle: #313335;
    --ma-light-border-subtle: #606467;

    pre.pygments {
        background: var(--ma-pre-bg);
    }

    .content img {
        filter: brightness(90%);
    }
}

.admonitionblock {
    border-left: 4px solid var(--ma-light-border-subtle);
    background: var(--ma-light-bg-subtle);
    font-style: italic;
}

.admonitionblock > table td.icon {
    display: none;
}

.note {
}

.exampleblock > .content {
    background: var(--ma-light-bg-subtle);
    border-color: #e0e0dc;
    box-shadow: none;
    border-left-color: var(--ma-light-border-subtle);
    border-left-style: solid;
    border-right: none;
    border-width: 0 0 0 4px;
    border-radius: 0;
    font-style: italic;
}

table {
    background: var(--ma-body-bg);
}

table thead, table tfoot {
    background: var(--ma-secondary-bg);
}

table thead tr th, table thead tr td, table tfoot tr th, table tfoot tr td {
    /*color: rgba(0, 0, 0, .8);*/
    color: var(--ma-body-color);
}

table.tableblock, th.tableblock, td.tableblock {
    border: 0 solid var(--ma-border-color);
}

body {
    font-family: var(--ma-font-sans-serif);
    background: var(--ma-body-bg);
    color: var(--ma-body-color);
    scrollbar-color: #9F9F9F #0000;
    scrollbar-width: thin;
}

table tr th, table tr td {
    color: var(--ma-body-color);
}

.content img {
    background: #fff;
    border-radius: 8px;
    padding: 16px;
    /*filter: brightness(90%);*/
}

pre code, pre pre {
    color: var(--ma-body-color);
    font-style: normal !important;
}

:not(pre):not([class^=L]) > code {
    font-size: .9375em;
    font-style: normal !important;
    font-family: var(--ma-font-monospace);
    letter-spacing: 0;
    padding: .1em .5ex;
    word-spacing: -.15em;
    color: var(--ma-body-color);
    /*background: #f7f7f8;*/
    background: var(--ma-secondary-bg);
    border-radius: 4px;
    line-height: 1.45;
    text-rendering: optimizeSpeed;
}

.literalblock pre, .listingblock > .content > pre {
    border: 1px solid var(--ma-border-color);
}

::-webkit-scrollbar-thumb {
    background: #ff00ae;
}

a {
    color: var(--ma-blue);
    text-decoration: none;
}

a:hover,a:focus{
    color: var(--ma-blue);
}

body.toc2 { 
    padding-top: var(--ma-nav-height);
}

#toc.toc2 {
    background: var(--ma-body-bg);
    border-right: none;
    top: var(--ma-nav-height);
    height: calc(100% - var(--ma-nav-height));
}

#toc.toc2 a {
    color: var(--ma-body-color);
}

#toctitle {
    color: var(--ma-body-color);
}

h2, h3, h4, h5 {
    color: var(--ma-body-color);
}

h2, h3, h4, h5, table, .dlist {
    scroll-margin-top: calc(var(--ma-nav-height) + 10px);
}

#header>h1:first-child {
    color: var(--ma-body-color);
}

h1, h2, h3, #toctitle, .sidebarblock>.content>.title, h4, h5, h6 {
    color: var(--ma-body-color);
}

.admonitionblock>table td.content {
    color: var(--ma-body-color);
    border-left: none;
}

/* table captions */
table.tableblock.fit-content > caption.title {
    white-space: normal;
    width: auto;
}

/* captions */
.subheader, .admonitionblock td.content>.title, .audioblock>.title, .exampleblock>.title, .imageblock>.title, .listingblock>.title, .literalblock>.title, .stemblock>.title, .openblock>.title, .paragraph>.title, .quoteblock>.title, table.tableblock>.title, .verseblock>.title, .videoblock>.title, .dlist>.title, .olist>.title, .ulist>.title, .qlist>.title, .hdlist>.title {
    color: var(--ma-body-color);
}

/*
@media screen and (min-width: 1280px) {

    #toc.toc2 {
        width: 30em;
    }

    body.toc2 {
        padding-left: 30em;
        padding-right: 0;
    }

}
*/

/* scrollspy styles */
.active {
    color: #BD0023;
    background-color: rgba(0, 0, 0, 0.1);
    border-radius: 5px;
}

/* header styles */
.ma-header {
    background-color: #014376;
    position: fixed;
    top: 0;
    left: 0; 
    height: var(--ma-nav-height); 
    width: 100%; 
    z-index: 2000;
    box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 0.2rem, rgba(0, 0, 0, 0.2) 0px 0.2rem 0.4rem;
    transition: transform 0.25s cubic-bezier(0.1, 0.7, 0.1, 1), box-shadow 0.25s;
}

.ma-header-content {
    margin-left: auto;
    margin-right: auto;
    max-width: 61rem;
    border: 1px solid red
}

.nav-button {
    color: #fff;
    width: 30px;
    height: 30px;
}

.nav-button svg {
    width: 100%;
    height: 100%;
}

#header > h1, #header > .details {
    display: none;
}

.vertical-text {
    transform: rotate(-90deg) translate(-11em, 0);
    transform-origin: left top 0;
    float: left;
    display: inline-block;
    white-space: nowrap;
    width: 1em;
    height: 11em;
}
</style>

<script>
// hide / show the Table of Contents (TOC)
function toggleTOC() {
  var toc = document.getElementById("toc");
  var body = document.getElementsByTagName("body")[0];

  if (toc.style.display === "none") {
      toc.style.display = "block";
      body.classList.remove("toc-hidden");
  } else {
      toc.style.display = "none";
      body.classList.add("toc-hidden");
  }
}

/*
window.addEventListener('DOMContentLoaded', () => {
    
    var theme = localStorage.getItem('theme');  
    
    if (theme != 'light' && theme != 'dark') {
        theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
        localStorage.setItem('theme', theme);
    }
    
    document.documentElement.setAttribute('data-ma-theme', theme);
})

function toggleTheme() {

    var currentTheme = document.documentElement.getAttribute('data-ma-theme');
    
    var newTheme = currentTheme == 'dark' ? 'light' : 'dark';
    
    localStorage.setItem('theme', newTheme);
    
    document.documentElement.setAttribute('data-ma-theme', newTheme);
}
*/
</script>

<script src="common/js/color-theme.js" defer></script>
<script src="common/js/scrollspy.js" defer></script>

<style>
.nav-yy svg {
    width: 22px;
    height: 22px;
    vertical-align: middle;
}
</style>

<div class="ma-header" style="display: flex; padding: 0 5px; align-items: center;">
  <a href="https://modelica.org/"><img src="images/m-ball.svg" style="padding: 10px; height: 50px; align-self: flex-start;"/></a>
  <span style="flex-grow: 1;"></span>

  <a href="#" onclick="toggleTOC()" class="nav-button" style="padding: 5px;">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-columns-reverse" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M0 .5A.5.5 0 0 1 .5 0h2a.5.5 0 0 1 0 1h-2A.5.5 0 0 1 0 .5m4 0a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1h-10A.5.5 0 0 1 4 .5m-4 2A.5.5 0 0 1 .5 2h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m4 0a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m-4 2A.5.5 0 0 1 .5 4h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m4 0a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5m-4 2A.5.5 0 0 1 .5 6h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m4 0a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5m-4 2A.5.5 0 0 1 .5 8h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m4 0a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5m-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m4 0a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1h-10a.5.5 0 0 1-.5-.5m-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m4 0a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5m-4 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m4 0a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5"/></svg>
  </a>

  <a onclick="toggleTheme()" class="nav-button" style="padding: 5px; margin-left: 10px;">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-half" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 0 8 1zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16"/></svg>
  </a>

  <div style="height: 30px; color: white; margin: 5px 10px 0 15px">
    <div style="display: inline-block; vertical-align: top; margin-top: 2px" class="nav-yy">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-git" viewBox="0 0 16 16">
        <path d="M15.698 7.287 8.712.302a1.03 1.03 0 0 0-1.457 0l-1.45 1.45 1.84 1.84a1.223 1.223 0 0 1 1.55 1.56l1.773 1.774a1.224 1.224 0 0 1 1.267 2.025 1.226 1.226 0 0 1-2.002-1.334L8.58 5.963v4.353a1.226 1.226 0 1 1-1.008-.036V5.887a1.226 1.226 0 0 1-.666-1.608L5.093 2.465l-4.79 4.79a1.03 1.03 0 0 0 0 1.457l6.986 6.986a1.03 1.03 0 0 0 1.457 0l6.953-6.953a1.03 1.03 0 0 0 0-1.457"/>
      </svg>
    </div>
    <div style="display: inline-block; font-size: 15px; margin-left: 8px">
      Modelica Language Specification
      <div style="font-size: 0.7rem">
        3.7-dev
      </div>
    </div>
  </div>

</div>

<div style="text-align: center">

    <picture>
        <source media="(prefers-color-scheme: light)" srcset="images/light/Modelica-Language.svg">
        <source media="(prefers-color-scheme: dark)" srcset="images/dark/Modelica-Language.svg">
        <img src="images/light/Modelica-Language.svg" alt="Modelica Language" style="width: 20em; margin: 4em;">
    </picture>

    <p style="font-size: 1.5em;">Modelica&reg; - A Unified Object-Oriented Language for Systems Modeling</p>
    <p style="font-size: 1.5em;">Language Specification</p>
    <p style="font-size: 1.5em;">Version 
++++
{revnumber}
++++
    </p>
    <p style="font-size: 1em;">
++++
{revdate}
++++
    </p>
    <p style="font-size: 1em;">Modelica Association</p>
</div>
++++

include::docs/0___preface.adoc[]

include::docs/1___introduction.adoc[]

include::docs/2___lexicalstructure.adoc[]

include::docs/3___operatorsandexpressions.adoc[]

include::docs/4___classes.adoc[]

include::docs/5___scoping.adoc[]

include::docs/6___interface.adoc[]

include::docs/7___inheritance.adoc[]

include::docs/8___equations.adoc[]

include::docs/9___connectors.adoc[]

include::docs/10__arrays.adoc[]

include::docs/11__statements.adoc[]

include::docs/12__functions.adoc[]

include::docs/13__packages.adoc[]

include::docs/14__overloaded.adoc[]

include::docs/15__stream.adoc[]

include::docs/16__synchronous.adoc[]

include::docs/17__statemachines.adoc[]

include::docs/18__annotations.adoc[]

include::docs/19__unitexpressions.adoc[]

include::docs/20__library.adoc[]

include::docs/A___syntax.adoc[]

include::docs/B___dae.adoc[]

include::docs/C___derivationofstream.adoc[]

include::docs/D___revisions.adoc[]

include::docs/E___bibliography.adoc[]